### ISSUE TITLE
CKAN borked install

### ISSUE THREAD

**Issue by MarsMullo** [linuxgurugamer/WaypointManager#4]
Waypoint manager will not install through CKAN because toolbar manager is not current. Must be none manually.

**Comment by linuxgurugamer** [comment]
Next time, give some details, such as what version of the game you are playing.  
Also, this is not an "issue",it's more of a tech support request, as such, the forum would be a better place to post, because other people may see it before me.

I'm going to guess that you are running 1.10.10.
In this case, you just need to tell CKAN that all 1.8 & 1.9 mods are compatible, at the main CKAN screen click **Settings->Compatible KSP Versions**, and add check marks next to the 1.8 & 1.9 lines

**Comment by MarsMullo** [comment]
Thank you. Your the best.
